Add rcon command function with layer
CFC-Servers/cfc_nanny_lambda_functions pull request #5
Opened 2020-11-24 20:55 UTC by brandonsturgeon

2020-11-26 05:52 UTC, plally commented on cfc-nanny/layers/lambda_responses/__init__.py
> +from .lambda_responses import *
i dont think you need this init file, or the init files in other layers

2020-11-26 05:54 UTC, plally commented on cfc-nanny/layers/response_caching/response_caching.py
> +class ResponseCache():
```suggestion
class ResponseCache:
```

2020-11-27 00:16 UTC, plally requested changes

2020-11-27 00:16 UTC, plally commented on cfc-nanny/template.yaml
> +Metadata:
will this just not work at all if its not under Metadata, feels weird putting stuff under a key thats used for other things

2020-11-27 00:16 UTC, plally commented on cfc-nanny/template.yaml
> +    cfctest: &cfctest_rcon
might be clearer if this was called cftest_rcon_env and cfc3_ron_env 
because CFCTestRcon is a function

2020-11-27 02:15 UTC, brandonsturgeon commented on cfc-nanny/template.yaml
> +Metadata:
Yeah it's super strict about which keys are allowed, so anything other than the allowed keys will throw an error during deployment. This is the only place that it works

2020-11-27 02:17 UTC, brandonsturgeon commented on cfc-nanny/layers/lambda_responses/lambda_responses.py
> +        errors = self.errors
This whole thing is a complicated way of avoiding just having a function, so it's already a little wonky.

In this case, though, I think duplicating the init methods doesn't add any value. `Response` already takes those values in and defaults them to `None`.

2020-11-27 03:04 UTC, merged